name: Format Code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Format code
      run: black .

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
    
    - name: Commit and create PR if changes
      if: steps.git-check.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      env:
        commit-message: "Formatted code with black"
        branch: "code-formatter-brr/lol"
        base: ${{ github.head_ref }}
    
