name: Test Application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Format code
      run: black .

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
    - name: Commit and create PR if changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git remote set-url origin git@github.com:SomethingGeneric/flaskpress.git
        git checkout -b formatter
        git commit -am "Apply black formatting"
        git push -u origin formatter
        gh pr create --title "Apply black formatting" --body "This PR applies black formatting to the codebase." --base main
    - name: Run tests
      run: python -m unittest
