name: Test Application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Format code
      run: black .

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
    - name: Set GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
    
    - name: Commit and create PR if changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit -am "Apply black formatting"
        gh pr create --title "Apply black formatting" --body "This PR applies black formatting to the codebase." --base main
    - name: Run tests
      run: python -m unittest
